apiVersion: v1
kind: Pod
metadata:
  name: authelia
  labels:
    app: authelia
spec:
  restartPolicy: Always
  containers:
  - name: authelia
    image: docker.io/authelia/authelia:4
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: DOMAIN
      value: "${site.env.domain}"
    - name: SESSION_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.session}
    - name: STORAGE_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.storage}
    - name: OIDC_HMAC_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.hmac}
    - name: AUTHELIA_SESSION_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.session}
    - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.storage}
    - name: X_AUTHELIA_CONFIG_FILTERS
      value: template
    ports:
    - containerPort: 9091
    volumeMounts:
    - name: config
      mountPath: /config/configuration.yml
      readOnly: true
    - name: userdb
      mountPath: /config/userdb
    - name: data
      mountPath: /data
  volumes:
  - name: config
    hostPath:
      path: "${component.dir}/configuration.yml"
  - name: userdb
    hostPath:
      path: "${site.data.roots.appdata}/authelia"
  - name: data
    hostPath:
      path: "${site.data.roots.appdata}/authelia/data"
