apiVersion: v1
kind: Pod
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  restartPolicy: Always
  containers:
  - name: vaultwarden
    image: docker.io/vaultwarden/server:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: DOMAIN
      value: "https://pw.${site.env.domain}"
    - name: ADMIN_TOKEN
      valueFrom:
        secretKeyRef:
          name: ${secrets.vaultwarden.admin_token}
    - name: SIGNUPS_ALLOWED
      value: "${site.env.signups_allowed}"
    - name: WEBSOCKET_ENABLED
      value: "true"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data
      mountPath: /data

  volumes:
  - name: data
    hostPath:
      path: ${site.data.roots.appdata}/vaultwarden
