apiVersion: v1
kind: Pod
metadata:
  name: immich
  labels:
    app: immich
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "${NAS_LAN_IP}"
    hostnames:
      - "auth.${DOMAIN}"
  containers:
  - name: database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    env:
    - name: POSTGRES_PASSWORD
      value: "${IMMICH_DB_PASSWORD}"
    - name: POSTGRES_USER
      value: immich
    - name: POSTGRES_DB
      value: immich
    volumeMounts:
    - name: pg
      mountPath: /var/lib/postgresql/data
  - name: redis
    image: docker.io/valkey/valkey:9
  - name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    env:
    - name: TZ
      value: "${TZ}"
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: ml
      mountPath: /cache
  - name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    env:
    - name: TZ
      value: "${TZ}"
    - name: DB_HOSTNAME
      value: "127.0.0.1"
    - name: DB_USERNAME
      value: immich
    - name: DB_PASSWORD
      value: "${IMMICH_DB_PASSWORD}"
    - name: DB_DATABASE_NAME
      value: immich
    - name: REDIS_HOSTNAME
      value: "127.0.0.1"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    ports:
    - containerPort: 2283
    volumeMounts:
    - name: upload
      mountPath: /data
    - name: photos
      mountPath: /mnt/photos
    - name: users
      mountPath: /mnt/users
  volumes:
  - name: pg
    persistentVolumeClaim:
      claimName: immich-postgres
  - name: ml
    persistentVolumeClaim:
      claimName: immich-ml-cache
  - name: upload
    persistentVolumeClaim:
      claimName: immich-upload
  - name: photos
    hostPath:
      path: "${NFS_SHARED}/photos"
  - name: users
    hostPath:
      path: "${NFS_USERS}"
