apiVersion: v1
kind: Pod
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  restartPolicy: Always
  containers:
  - name: openldap
    image: docker.io/osixia/openldap:1.5.0
    env:
    - name: TZ
      value: "${TZ}"
    - name: LDAP_ORGANISATION
      value: site
    - name: LDAP_DOMAIN
      value: "${DOMAIN}"
    - name: LDAP_ADMIN_PASSWORD
      value: "${secrets.openldap.admin_password}"
    ports:
    - containerPort: 389
    volumeMounts:
    - name: data
      mountPath: /var/lib/ldap
    - name: config
      mountPath: /etc/ldap/slapd.d
  volumes:
  - name: data
    hostPath:
      path: "${DATA_ROOT}/system/openldap/data"
  - name: config
    hostPath:
      path: "${DATA_ROOT}/system/openldap/config"
