apiVersion: v1
kind: Pod
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  restartPolicy: Always
  containers:
  - name: openldap
    image: docker.io/osixia/openldap:1.5.0
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: LDAP_ORGANISATION
      value: site
    - name: LDAP_DOMAIN
      value: "${site.env.domain}"
    - name: LDAP_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${secrets.openldap.admin_password}
    ports:
    - containerPort: 389
    volumeMounts:
    - name: data
      mountPath: /var/lib/ldap
    - name: config
      mountPath: /etc/ldap/slapd.d
  volumes:
  - name: data
    hostPath:
      path: "${site.data.roots.appdata}/openldap/data"
  - name: config
    hostPath:
      path: "${site.data.roots.appdata}/openldap/config"
