apiVersion: v1
kind: Pod
metadata:
  name: openreader
  labels:
    app: openreader
spec:
  restartPolicy: Always
  containers:
  - name: openreader
    image: ghcr.io/richardr1126/openreader:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: BASE_URL
      value: "https://read.${site.env.domain}"
    - name: AUTH_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.openreader.auth_secret}
    - name: AUTH_TRUSTED_ORIGINS
      value: "https://read.${site.env.domain},https://openreader.${site.env.domain},https://reader.${site.env.domain}"
    - name: ADMIN_EMAILS
      value: "admin@${site.env.domain}"
    ports:
    - containerPort: 3003
    volumeMounts:
    - name: docstore
      mountPath: /app/docstore

  volumes:
  - name: docstore
    hostPath:
      path: ${host.data.roots.appdata}/openreader
