apiVersion: v1
kind: Pod
metadata:
  name: restic
  labels:
    app: restic
spec:
  restartPolicy: Always
  containers:
  - name: restic
    image: docker.io/restic/restic:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: RESTIC_REPOSITORY
      value: "rest:http://${site.env.upstream}:8000/${host.name}"
    - name: RESTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${secrets.restic.password}
    - name: RESTIC_CACHE_DIR
      value: "/cache"
    - name: UPTIME_KUMA_PUSH_URL
      value: "${site.env.uptime_kuma_push_url}"
    volumeMounts:
    - name: data
      mountPath: /data
      readOnly: true
    - name: cache
      mountPath: /cache
    - name: script
      mountPath: /backup.sh
      readOnly: true
    command: ["/bin/sh", "/backup.sh"]

  volumes:
  - name: data
    hostPath:
      path: ${site.data.roots.appdata}
  - name: cache
    hostPath:
      path: ${site.data.roots.appdata}/restic
  - name: script
    hostPath:
      path: ${component.dir}/backup.sh
