apiVersion: v1
kind: Pod
metadata:
  name: glances-mantle
  labels:
    app: glances-mantle
spec:
  restartPolicy: Always
  hostPID: true
  containers:
  - name: glances
    image: docker.io/nicolargo/glances:ubuntu-latest-full
    env:
    - name: TZ
      value: "${TZ}"
    - name: GLANCES_OPT
      value: "-w --disable-plugin docker"
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: compute,utility
    ports:
    - containerPort: 61208
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: conf
      mountPath: /etc/glances/glances.conf
      readOnly: true
    - name: osrel
      mountPath: /etc/os-release
      readOnly: true
    - name: sys
      mountPath: /sys
      readOnly: true
    - name: win
      mountPath: /mnt/windows
      readOnly: true
  volumes:
  - name: conf
    hostPath:
      path: "${COMPONENT_DIR}/glances.conf"
  - name: osrel
    hostPath:
      path: /etc/os-release
  - name: sys
    hostPath:
      path: /sys
  - name: win
    hostPath:
      path: /mnt/c
