- Apps:

    - Local:
        - OpenCloud:
            id: opencloud
            href: https://cloud.{{HOMEPAGE_VAR_DOMAIN}}
            server: core
            container: opencloud
            icon: opencloud.svg
            description: Files
        - Immich:
            id: immich
            href: https://photos.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: immich
            icon: immich.svg
            description: Photos
        - Home Assistant:
            id: homeassistant
            href: https://auto.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: homeassistant
            icon: home-assistant.svg
            description: Home Automation
        - Vaultwarden:
            id: vaultwarden
            href: https://pass.{{HOMEPAGE_VAR_DOMAIN}}
            server: core
            container: vaultwarden
            icon: bitwarden.svg
            description: Passwords
        - Jellyfin:
            id: jellyfin
            href: https://watch.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: jellyfin
            icon: jellyfin.svg
            description: Watch Movies & TV
        - Seerr:
            href: https://request.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: seerr
            icon: seerr.svg
            description: Request Movies & TV

    - Web:
        - Gmail:
            href: https://gmail.com
            icon: gmail.svg
        - Drive:
            href: https://drive.google.com
            icon: google-drive.svg
        - YouTube:
            href: https://youtube.com
            icon: youtube.svg
        - Spotify:
            href: https://open.spotify.com
            icon: spotify.svg
        - ChatGPT:
            href: https://chatgpt.com
            icon: chatgpt.svg
        - Amazon:
            href: https://amazon.com/gp/css/order-history
            icon: amazon.svg
        - Discord:
            href: https://discord.com/channels/@me
            icon: discord.svg
        - WhatsApp:
            id: whatsapp
            href: https://web.whatsapp.com
            icon: whatsapp.svg
        - Fidelity:
            href: https://www.fidelity.com
            icon: fidelity.svg
        - GitHub:
            href: https://github.com
            icon: github-light.svg
            
- System:

    - Media:
        - Jellyfin:
            href: https://watch.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: jellyfin
            icon: jellyfin.svg
            description: Library
        - qBittorrent:
            href: https://down.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: qbittorrent
            icon: qbittorrent.svg
            description: Downloads      
        - Prowlarr:
            href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: prowlarr
            icon: prowlarr.svg
            description: Indices      
        - Radarr:
            href: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: radarr
            icon: radarr.svg
            description: Request Movies    
        - Sonarr:
            href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: sonarr
            icon: sonarr.svg
            description: Request TV Shows

    - Platform:
        - Gitea:
            href: https://git.{{HOMEPAGE_VAR_DOMAIN}}
            server: core
            container: gitea
            icon: gitea.svg
            description: Version Control
        - Komodo:
            href: https://ops.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_NAS_LAN_IP}}:9120
            icon: docker.svg
            description: Deployment
        - OpenMediaVault:
            href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_NAS_LAN_IP}}:81
            icon: openmediavault.svg
            description: Storage
        - Grafana:
            href: https://stats.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: grafana
            icon: grafana.svg
            description: Monitoring
        #    widget:
        #      type: grafana
        #      url: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:3000
        #      key: "{{HOMEPAGE_VAR_GRAFANA_KEY}}"
        - Prometheus:
            href: https://metrics.{{HOMEPAGE_VAR_DOMAIN}}
            server: periphery
            container: prometheus
            icon: prometheus.svg
            description: Metrics
        - Authelia:
            href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
            server: core
            container: authelia
            icon: authelia.svg
            description: Authentication

    - Network:
        - Pi-hole:
            href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin
            server: core
            container: pihole
            icon: pi-hole.svg
            description: DNS
            widget:
                type: pihole
                url: http://pihole:80
                version: 6
                fields:
                - queries
                - blocked_percent
                - gravity
        # - Pi-hole Periphery:
        #    href: https://dns2.{{HOMEPAGE_VAR_DOMAIN}}/admin
        #    siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8083/admin
        #    icon: pi-hole.svg
        #    description: DNS (Secondary)
        - WireGuard:
            href: https://vpn.{{HOMEPAGE_VAR_DOMAIN}}
            server: core
            container: wireguard
            icon: wireguard.svg
            description: VPN
        - Linksys EA8300:
            href: https://wifi.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: https://192.168.1.1/
            icon: linksys.svg
            description: Router
        - HP LaserJet M29w:
            href: https://print.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: https://192.168.1.113/
            icon: hp.svg
            description: Printer