- Apps:

    - Local:
        - Nextcloud:
            href: https://nextcloud.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8080
            icon: nextcloud.png
            description: Docs / Photos
        - Home Assistant:
            href: https://ha.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8123
            icon: home-assistant.png
            description: Home Automation
        - Vaultwarden:
            href: https://pw.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://vaultwarden:80
            icon: bitwarden.png
            description: Passwords
        - Jellyfin (client):
            href: jellyfin://watch.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8096
            icon: jellyfin.png
            description: Watch Movies & TV
        - Seerr:
            href: https://request.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:5055
            icon: seerr.png
            description: Request Movies & TV

    - Web:
        - Gmail:
            href: https://gmail.com
            icon: gmail.png
        - Drive:
            href: https://drive.google.com
            icon: google-drive.png
        - YouTube:
            href: https://youtube.com
            icon: youtube.png
        - Spotify:
            href: https://open.spotify.com
            icon: spotify.png
        - ChatGPT:
            href: https://chatgpt.com
            icon: chatgpt.png
        - Amazon:
            href: https://amazon.com/gp/css/order-history
            icon: amazon.png
        - Fidelity:
            href: https://www.fidelity.com
            icon: fidelity.png
        - Discord:
            href: https://discord.com/channels/@me
            icon: discord.png
        - WhatsApp:
            href: https://web.whatsapp.com
            icon: whatsapp.png

- System:

    - Media:
        - Jellyfin:
            href: https://watch.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8096
            icon: jellyfin.png
            description: Library
        - qBittorrent:
            href: https://qbit.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8081
            icon: qbittorrent.png
            description: Downloads      
        - Prowlarr:
            href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:9696
            icon: prowlarr.png
            description: Indices      
        - Radarr:
            href: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:7878
            icon: radarr.png
            description: Request Movies    
        - Sonarr:
            href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8989
            icon: sonarr.png
            description: Request TV Shows

    - Platform:
        - Komodo:
            href: https://ops.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_NAS_LAN_IP}}:9120
            icon: docker.png
            description: Deployment
        - OpenMediaVault:
            href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_NAS_LAN_IP}}:81
            icon: openmediavault.png
            description: Storage
        - Grafana:
            href: https://grafana.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:3000
            icon: grafana.png
            description: Monitoring
        #    widget:
        #      type: grafana
        #      url: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:3000
        #      key: "{{HOMEPAGE_VAR_GRAFANA_KEY}}"
        - Prometheus:
            href: https://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:9090
            icon: prometheus.png
            description: Metrics
        - Authelia:
            href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://authelia:9091/api/health
            icon: authelia.png
            description: Authentication

    - Network:
        - Pi-hole:
            href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin
            siteMonitor: http://pihole:80/admin
            icon: pi-hole.png
            description: DNS
            widget:
              type: pihole
              url: http://pihole:80
              version: 6
              fields:
                - queries
                - blocked_percent
                - gravity
       # - Pi-hole Periphery:
       #    href: https://dns2.{{HOMEPAGE_VAR_DOMAIN}}/admin
       #    siteMonitor: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:8083/admin
       #    icon: pi-hole.png
       #    description: DNS (Secondary)
        - WireGuard:
            href: https://vpn.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://wireguard:51821
            icon: wireguard.png
            description: VPN