title: Home
theme: dark
headerStyle: clean
hideVersion: true
statusStyle: dot
background:
  image: /images/background.png
  #brightness: 50
 #opacity: 0
cardBlur: sm

#layout:
#  Platform:
#    style: row
#    columns: 4
#  Media:
#    style: row
#    columns: 4
#  Cloud:
#    style: row
#    columns: 2
#  Monitor:
#    style: row
#    columns: 2
