title: Home
theme: dark
headerStyle: clean
hideVersion: true
statusStyle: dot
background:
  image: /images/background.png
  opacity: 80
  brightness: 50

layout:
  Apps:
    style: column
    rows: 2
  System:
    styled: row
    Platform:
      style: column
    Network:
      style: column
    Downloads:
      style: column

#  Platform:
#    style: row
#    columns: 4
#  Media:
#    style: row
#    columns: 4
#  Cloud:
#    style: row
#    columns: 2
#  Monitor:
#    style: row
#    columns: 2
