title: Home
theme: dark
headerStyle: clean
hideVersion: true
statusStyle: dot

background:
  image: /images/background.png
  opacity: 80
  brightness: 50

layout:
  style: row
  columns: 2
  Apps:
    header: false
  System:
    header: false
