- openmeteo:
    latitude: 34.19107278206662
    longitude: -118.48053034784378
    timezone: America/Los_Angeles
    units: imperial
    cache: 5

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: medium

#- search:
#    provider: duckduckgo
#    target: _blank

- glances:
    url: http://glances:61208
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk:
      - /mnt/data

#- glances:
#    url: http://{{HOMEPAGE_VAR_HTPC_UPSTREAM}}:61208
#    version: 4
#    cpu: true
#    mem: true
#    uptime: true
#    disk:
#      - /mnt/windows
#    label: Periphery
