services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "8123:8123"
    volumes:
      - ${DATA_ROOT}/system/periphery/homeassistant:/config
      - ./configuration.yaml:/config/configuration.yaml
    # wifi / integrations only; no USB radio passthrough
