apiVersion: v1
kind: Pod
metadata:
  name: bytestash
  labels:
    app: bytestash
spec:
  hostAliases:
  - ip: "${site.networking.loopback}"
    hostnames:
      - "auth.${site.env.domain}"

  restartPolicy: Always
  containers:
  - name: bytestash
    image: ghcr.io/jordan-dalby/bytestash:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: BASE_PATH
      value: ""
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.bytestash.jwt}
          key: value
    - name: TOKEN_EXPIRY
      value: "24h"
    - name: ALLOW_NEW_ACCOUNTS
      value: "${site.env.bytestash_allow_new_accounts}"
    - name: DEBUG
      value: "false"
    - name: DISABLE_ACCOUNTS
      value: "false"
    - name: DISABLE_INTERNAL_ACCOUNTS
      value: "false"
    - name: ALLOWED_HOSTS
      value: "snip.${site.env.domain}"
    - name: OIDC_ENABLED
      value: "true"
    - name: OIDC_DISPLAY_NAME
      value: "Authelia"
    - name: OIDC_ISSUER_URL
      value: "https://auth.${site.env.domain}"
    - name: OIDC_CLIENT_ID
      value: "bytestash"
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.oidc_client_secret}
          key: value
    - name: OIDC_SCOPES
      value: "openid profile email"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: data
      mountPath: /data/snippets

  volumes:
  - name: data
    hostPath:
      path: ${site.data.roots.appdata}/bytestash
