apiVersion: v1
kind: Pod
metadata:
  name: scriberr
  labels:
    app: scriberr
spec:
  restartPolicy: Always
  containers:
  - name: scriberr
    image: ghcr.io/rishikanthc/scriberr-cuda:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: PUID
      value: "10001"
    - name: PGID
      value: "10001"
    - name: APP_ENV
      value: "production"
    - name: ALLOWED_ORIGINS
      value: "https://voice.${site.env.domain},https://scribe.${site.env.domain},https://transcribe.${site.env.domain},https://scriberr.${site.env.domain}"
    - name: NVIDIA_VISIBLE_DEVICES
      value: "${host.resources.gpu.gpu0.uuid}"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "compute,utility"
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /app/data
    - name: whisper
      mountPath: /app/whisperx-env
    resources:
      limits:
        ${host.resources.gpu.gpu0.resource}: 1

  volumes:
  - name: data
    hostPath:
      path: ${host.data.roots.appdata}/scriberr/data
  - name: whisper
    hostPath:
      path: ${host.data.roots.appdata}/scriberr/whisperx
