apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  restartPolicy: Always
  containers:
  - name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${TZ}"
    - name: PUID
      value: "${PUID}"
    - name: PGID
      value: "${PGID}"
    - name: WEBUI_PORT
      value: "8081"
    - name: TORRENTING_PORT
      value: "6881"
    ports:
    - containerPort: 8081
    - containerPort: 6881
    volumeMounts:
    - name: config
      mountPath: /config
    - name: downloads
      mountPath: /downloads
    - name: media
      mountPath: /data/media
    - name: init
      mountPath: /custom-cont-init.d
      readOnly: true

  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: qbittorrent-config
  - name: downloads
    hostPath:
      path: ${NFS_SHARED}/downloads
  - name: media
    hostPath:
      path: ${NFS_SHARED}/media
  - name: init
    hostPath:
      path: ${COMPONENT_DIR}/custom-cont-init.d
