apiVersion: v1
kind: Pod
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  restartPolicy: Always
  containers:
  - name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: NAS_LAN_IP
      value: "${site.networking.ingress.host.ip}"
    ports:
    - containerPort: 8123
    volumeMounts:
    - name: config
      mountPath: /config
    - name: ensure
      mountPath: /ensure-http
      readOnly: true
    command: ["/bin/sh", "-c", "python3 /ensure-http/patch.py && exec /init"]

  volumes:
  - name: config
    hostPath:
      path: ${host.data.roots.appdata}/homeassistant
  - name: ensure
    hostPath:
      path: ${component.dir}/ensure-http
