apiVersion: v1
kind: Pod
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  restartPolicy: Always
  containers:
  - name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${TZ}"
    - name: NAS_LAN_IP
      value: "${NAS_LAN_IP}"
    ports:
    - containerPort: 8123
    volumeMounts:
    - name: config
      mountPath: /config
    - name: ensure
      mountPath: /ensure-http
      readOnly: true
    command: ["/bin/sh", "-c", "python3 /ensure-http/patch.py && exec /init"]

  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: ha-config
  - name: ensure
    hostPath:
      path: ${COMPONENT_DIR}/ensure-http
