apiVersion: v1
kind: Pod
metadata:
  name: glances
  labels:
    app: glances
spec:
  restartPolicy: Always
  containers:
  - name: glances
    image: docker.io/nicolargo/glances:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${TZ}"
    - name: GLANCES_OPT
      value: "-w --disable-plugin docker"
    ports:
    - containerPort: 61208
    volumeMounts:
    - name: conf
      mountPath: /etc/glances/glances.conf
      readOnly: true
    - name: osrel
      mountPath: /etc/os-release
      readOnly: true
    - name: sys
      mountPath: /sys
      readOnly: true
    - name: data
      mountPath: /mnt/data
      readOnly: true
    securityContext:
      privileged: false

  volumes:
  - name: conf
    hostPath:
      path: ${COMPONENT_DIR}/glances.conf
  - name: osrel
    hostPath:
      path: /etc/os-release
  - name: sys
    hostPath:
      path: /sys
  - name: data
    hostPath:
      path: ${DATA_ROOT}
