apiVersion: v1
kind: Pod
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "${site.networking.ingress.host.ip}"
    hostnames:
      - "auth.${site.env.domain}"
  containers:
  - name: prometheus
    image: docker.io/prom/prometheus:latest
    command: ["/bin/sh", "-c", "sh /apply-config.sh && exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"]
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: NAS_LAN_IP
      value: "${site.networking.ingress.host.ip}"
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: tmpl
      mountPath: /etc/prometheus/prometheus.yml.template
      readOnly: true
    - name: apply
      mountPath: /apply-config.sh
      readOnly: true
    - name: data
      mountPath: /prometheus
  - name: grafana
    image: docker.io/grafana/grafana:latest
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: GF_SECURITY_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${secrets.monitoring.grafana_admin_password}
    - name: GF_SERVER_ROOT_URL
      value: "https://site.${site.env.domain}"
    - name: GF_AUTH_GENERIC_OAUTH_ENABLED
      value: "true"
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      value: grafana
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.oidc_client_secret}
    - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      value: "https://auth.${site.env.domain}/api/oidc/authorization"
    - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      value: "https://auth.${site.env.domain}/api/oidc/token"
    - name: GF_AUTH_GENERIC_OAUTH_API_URL
      value: "https://auth.${site.env.domain}/api/oidc/userinfo"
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: graf
      mountPath: /var/lib/grafana
  volumes:
  - name: tmpl
    hostPath:
      path: "${component.dir}/prometheus.yml.template"
  - name: apply
    hostPath:
      path: "${component.dir}/apply-config.sh"
  - name: data
    hostPath:
      path: "${host.data.roots.appdata}/monitoring/prometheus"
  - name: graf
    hostPath:
      path: "${host.data.roots.appdata}/monitoring/grafana"
