apiVersion: v1
kind: Pod
metadata:
  name: jotty
  labels:
    app: jotty
spec:
  hostAliases:
  - ip: "${site.networking.loopback}"
    hostnames:
      - "auth.${site.env.domain}"

  restartPolicy: Always
  containers:
  - name: jotty
    image: ghcr.io/fccview/jotty:latest
    imagePullPolicy: Always
    env:
    - name: TZ
      value: "${site.env.timezone}"
    - name: PUID
      value: "${host.roles.workload.uid}"
    - name: PGID
      value: "${host.roles.workload.gid}"
    - name: NODE_ENV
      value: "production"
    - name: APP_URL
      value: "https://notes.${site.env.domain}"
    - name: HTTPS
      value: "true"
    - name: AUTH_MODE
      value: "oidc"
    - name: OIDC_ISSUER
      value: "https://auth.${site.env.domain}"
    - name: OIDC_CLIENT_ID
      value: "jotty"
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: ${secrets.authelia.oidc_client_secret}
    - name: SSO_FALLBACK_LOCAL
      value: "yes"
    - name: OIDC_ADMIN_GROUPS
      value: "admins"
    - name: OIDC_USER_GROUPS
      value: "users"
    - name: OIDC_GROUPS_SCOPE
      value: "groups"
    - name: INTERNAL_API_URL
      value: "http://localhost:3000"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: data
      mountPath: /app/data
    - name: config
      mountPath: /app/config
    - name: cache
      mountPath: /app/.next/cache

  volumes:
  - name: data
    hostPath:
      path: ${site.data.roots.appdata}/system/jotty/data
  - name: config
    hostPath:
      path: ${site.data.roots.appdata}/system/jotty/config
  - name: cache
    hostPath:
      path: ${site.data.roots.appdata}/system/jotty/cache
