#!/usr/bin/env bash
# Site secret helpers. Sourced by core.sh. Writes /etc/infra-core/site.env.
# Requires: prompt, prompt_secret, rand, quote_s (or defines fallbacks).

: "${INFRA_DIR:=/etc/infra-core}"
: "${SITE_ENV:=${INFRA_DIR}/site.env}"
: "${ANSWERS:=${INFRA_DIR}/bootstrap-answers.env}"

_site_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_site_repo_root="$(cd "${_site_lib_dir}/../.." && pwd)"

if ! declare -F prompt >/dev/null 2>&1; then
  prompt() {
    local var="$1" message="$2" default="${3:-}" value
    if [[ -n "${default}" ]]; then
      read -r -p "${message} [${default}]: " value
      value="${value:-${default}}"
    else
      read -r -p "${message}: " value
    fi
    printf -v "${var}" '%s' "${value}"
  }
fi
if ! declare -F prompt_secret >/dev/null 2>&1; then
  prompt_secret() {
    local var="$1" message="$2" value
    read -r -s -p "${message}: " value
    echo
    printf -v "${var}" '%s' "${value}"
  }
fi
if ! declare -F rand >/dev/null 2>&1; then
  rand() { openssl rand -hex 24; }
fi
if ! declare -F quote_s >/dev/null 2>&1; then
  quote_s() { printf "%s" "$1" | sed "s/'/'\\\\''/g"; }
fi

site_needed_var_lines() {
  cat <<'EOF'
DOMAIN	prompt	Public/LAN domain (no scheme)
TZ	default	America/Los_Angeles
NAS_LAN_IP	prompt	LAN IP of this host (Core)
SURFACE_UPSTREAM	prompt	LAN IP of surface (Windows TV PC)
DATA_ROOT	fixed	${DATA_ROOT}
PUID	default	1000
PGID	default	1000
WG_HOST	prompt	Public DNS name for WireGuard (WAN)
CORE_SERVER	default	core
PIHOLE_DNS_PORT	default	15353
PIHOLE_WEB_PORT	default	8088
AUTHELIA_JWT_SECRET	generate
AUTHELIA_SESSION_SECRET	generate
AUTHELIA_STORAGE_ENCRYPTION_KEY	generate
AUTHELIA_OIDC_HMAC_SECRET	generate
AUTHELIA_FAIZ_PASSWORD	secret	Authelia password for faiz (admins)
AUTHELIA_DIANA_PASSWORD	secret	Authelia password for diana
OIDC_CLIENT_SECRET	generate
PIHOLE_WEBPASSWORD	secret	Pi-hole web password
WG_UI_PASSWORD	generate
VAULTWARDEN_ADMIN_TOKEN	generate
OPENCLOUD_ADMIN_PASSWORD	secret	OpenCloud admin password
NUT_REMOTE_PASSWORD	generate
RESTIC_PASSWORD	secret	Restic repo password
HOMEPAGE_ALLOWED_HOSTS	empty
EOF
}

# Snapshot the secret list to a file so `while read` never steals prompt stdin.
site_needed_var_file() {
  local f
  f="$(mktemp)"
  site_needed_var_lines >"${f}"
  printf '%s' "${f}"
}

site_ensure_var() {
  local key="$1" mode="$2" extra="${3:-}"
  local cur="${!key-}"
  if [[ -n "${cur}" ]]; then
    return 0
  fi
  case "${mode}" in
    prompt)
      if [[ "${key}" == "NAS_LAN_IP" ]]; then
        local detected
        detected=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || true)
        prompt "${key}" "${extra}" "${detected}"
      else
        prompt "${key}" "${extra}"
      fi
      ;;
    secret)
      prompt_secret "${key}" "${extra}"
      ;;
    generate)
      printf -v "${key}" '%s' "$(rand)"
      echo "Generated ${key}"
      ;;
    default)
      printf -v "${key}" '%s' "${extra}"
      ;;
    empty)
      printf -v "${key}" '%s' ""
      ;;
    fixed)
      if [[ "${extra}" == '${DATA_ROOT}' ]]; then
        printf -v "${key}" '%s' "${DATA_ROOT}"
      else
        printf -v "${key}" '%s' "${extra}"
      fi
      ;;
    *)
      echo "Unknown mode ${mode} for ${key}" >&2
      return 1
      ;;
  esac
}

site_ensure_site_vars() {
  local key mode extra list
  list="$(site_needed_var_file)"
  while IFS=$'\t' read -r key mode extra; do
    [[ -n "${key}" ]] || continue
    site_ensure_var "${key}" "${mode}" "${extra}"
  done <"${list}"
  rm -f "${list}"
  if [[ -z "${HOMEPAGE_ALLOWED_HOSTS:-}" && -n "${DOMAIN:-}" ]]; then
    HOMEPAGE_ALLOWED_HOSTS="dash.${DOMAIN},homepage.${DOMAIN},localhost:3000,127.0.0.1:3000"
  fi
}

site_write_site_env() {
  local tmp key mode extra val list
  tmp="$(mktemp)"
  list="$(site_needed_var_file)"
  {
    echo "# Generated by bootstrap; do not commit. chmod 600."
    while IFS=$'\t' read -r key mode extra; do
      [[ -n "${key}" ]] || continue
      val="${!key-}"
      printf "%s='%s'\n" "${key}" "$(quote_s "${val}")"
    done <"${list}"
  } >"${tmp}"
  rm -f "${list}"
  mkdir -p "$(dirname "${SITE_ENV}")"
  mv "${tmp}" "${SITE_ENV}"
  chmod 600 "${SITE_ENV}"
}

site_save_answers() {
  local old key mode extra val list
  old=$(umask)
  umask 077
  list="$(site_needed_var_file)"
  {
    echo "# Generated by bootstrap; do not commit."
    while IFS=$'\t' read -r key mode extra; do
      [[ -n "${key}" ]] || continue
      val="${!key-}"
      printf "%s='%s'\n" "${key}" "$(quote_s "${val}")"
    done <"${list}"
    if [[ -n "${DATA_ROOT:-}" ]]; then
      printf "DATA_ROOT='%s'\n" "$(quote_s "${DATA_ROOT}")"
    fi
  } >"${ANSWERS}"
  rm -f "${list}"
  umask "${old}"
}
